export const siteUrl = "https://sena-v.com"
export const gitHubUrl = "https://github.com/sena-v"
export const qiitaUrl = "https://qiita.com/sena_v"
export const twitterUrl = "https://twitter.com/card1nal_tetra"
export const siteSourceCodeUrl = "https://github.com/sena-v/blog.sena-v.com.next"
