name: Netlify

on:
  push:
    branches:
      - main

jobs:
  Check-type_lint_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: load or cache node dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: install npm package
        run: npm ci

      - name: Playwright install
        run: npx playwright install --with-deps

      # E2e実行前にnetlify側のデプロイを待機(2分)
      - name: Wait Before Invalidate
        run: sleep 120

      - name: Check e2e
        run: npx playwright e2e
