name: Netlify

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  Check / type / lint / build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v3
      - name: setup node latest
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: load or cache node dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: install npm package
        run: npm ci
      - name: type check
        run: npm run ci

  # Netlifyにデプロイ実施
  # - run: npx netlify-cli deploy --dir=./next
  #   env:
  #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
